"""dormitory_pilot

Revision ID: 0002_pilot
Revises: 0001_initial
Create Date: 2026-10-02 12:14:57.787701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_pilot'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_deletion_ledger',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('identity_digest', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pilot_rate_buckets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_pilot_rate_buckets_expires_at'), 'pilot_rate_buckets', ['expires_at'], unique=False)
    op.create_table('pilot_worker_heartbeats',
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('pilot_allocation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_allocation_history_closed_at'), 'pilot_allocation_history', ['closed_at'], unique=False)
    op.create_index(op.f('ix_pilot_allocation_history_user_id'), 'pilot_allocation_history', ['user_id'], unique=False)
    op.create_table('pilot_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'target_id', name='uq_pilot_block')
    )
    op.create_index(op.f('ix_pilot_blocks_actor_id'), 'pilot_blocks', ['actor_id'], unique=False)
    op.create_index(op.f('ix_pilot_blocks_target_id'), 'pilot_blocks', ['target_id'], unique=False)
    op.create_table('pilot_command_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'action', 'key', name='uq_pilot_command_receipt')
    )
    op.create_index(op.f('ix_pilot_command_receipts_created_at'), 'pilot_command_receipts', ['created_at'], unique=False)
    op.create_table('pilot_departures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('active_key', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_pilot_departure_status'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_key', name='uq_pilot_departure_active')
    )
    op.create_index(op.f('ix_pilot_departures_user_id'), 'pilot_departures', ['user_id'], unique=False)
    op.create_table('pilot_domain_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_domain_audit_action'), 'pilot_domain_audit', ['action'], unique=False)
    op.create_index(op.f('ix_pilot_domain_audit_created_at'), 'pilot_domain_audit', ['created_at'], unique=False)
    op.create_table('pilot_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('pool', sa.String(length=100), nullable=False),
    sa.Column('cycle', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='eligible', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('pilot_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active_key', sa.String(length=150), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('approvals', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending','needs_reconfirmation','accepted','rejected','cancelled','expired')", name='ck_pilot_invitation_status'),
    sa.CheckConstraint('capacity >= 2', name='ck_pilot_invitation_capacity'),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('active_key', name='uq_pilot_invitation_active')
    )
    op.create_index('ix_pilot_invitation_status_expiry', 'pilot_invitations', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_pilot_invitations_candidate_id'), 'pilot_invitations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_pilot_invitations_group_id'), 'pilot_invitations', ['group_id'], unique=False)
    op.create_index(op.f('ix_pilot_invitations_initiator_id'), 'pilot_invitations', ['initiator_id'], unique=False)
    op.create_table('pilot_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', 'user_id', name='uq_pilot_notification_event')
    )
    op.create_index(op.f('ix_pilot_notifications_user_id'), 'pilot_notifications', ['user_id'], unique=False)
    op.create_table('pilot_questionnaires',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('capacities', sa.JSON(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pilot_sessions',
    sa.Column('sid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('refresh_digest', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_pilot_sessions_expires_at'), 'pilot_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pilot_sessions_user_id'), 'pilot_sessions', ['user_id'], unique=False)
    op.create_table('pilot_support_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_pilot_support_cases_user_id'), 'pilot_support_cases', ['user_id'], unique=False)
    op.create_table('pilot_invitation_participants',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['pilot_invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id', 'user_id')
    )
    op.create_index(op.f('ix_pilot_invitation_participants_user_id'), 'pilot_invitation_participants', ['user_id'], unique=False)
    op.create_table('pilot_security_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('approved_email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['pilot_enrollments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_pilot_security_tokens_enrollment_id'), 'pilot_security_tokens', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_pilot_security_tokens_expires_at'), 'pilot_security_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pilot_security_tokens_user_id'), 'pilot_security_tokens', ['user_id'], unique=False)
    op.create_table('pilot_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('recipient_ref', sa.String(length=64), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('key_version', sa.String(length=30), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['pilot_security_tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_index('ix_pilot_outbox_due', 'pilot_outbox', ['status', 'next_attempt_at', 'lease_until'], unique=False)
    op.add_column('groups', sa.Column('membership_revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('groups', sa.Column('pool', sa.String(length=100), nullable=True))
    op.add_column('groups', sa.Column('cycle', sa.String(length=100), nullable=True))
    op.add_column('groups', sa.Column('reconciliation_required', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('rooms', sa.Column('pool', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('cycle', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('reconciliation_required', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('auth_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('account_status', sa.String(length=30), server_default='active', nullable=False))
    op.add_column('users', sa.Column('discovery_consent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('explanation_consent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('consent_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('notification_email', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('roommate_requests', sa.Column('reason', sa.String(length=100), nullable=True))
    # No behavior is inferred from v1 answers. Claims must verify the roster email.
    op.execute(sa.text("UPDATE users SET email_verified = false, auth_version = auth_version + 1 WHERE role <> 'admin'"))
    op.execute(sa.text("UPDATE refresh_sessions SET revoked_at = CURRENT_TIMESTAMP WHERE revoked_at IS NULL"))
    op.execute(sa.text("UPDATE auth_tokens SET used_at = CURRENT_TIMESTAMP WHERE used_at IS NULL"))
    connection = op.get_bind()
    pending = connection.execute(sa.text("SELECT id, sender_id, receiver_id FROM roommate_requests WHERE status = 'pending'")).fetchall()
    notices = sa.table('pilot_notifications', sa.column('user_id'), sa.column('event_key'), sa.column('kind'),
                       sa.column('message'), sa.column('entity_type'), sa.column('entity_id'), sa.column('read'), sa.column('created_at'))
    for invitation_id, sender_id, receiver_id in pending:
        for user_id in {sender_id, receiver_id}:
            connection.execute(notices.insert().values(user_id=user_id, event_key=f"legacy:{invitation_id}:policy_upgrade",
                kind='policy_upgrade', message='دعوت قبلی با تغییر سیاست بسته شد؛ پس از تأیید عضویت و پرسشنامهٔ جدید می‌توانید دعوت تازه بسازید.',
                entity_type='legacy_request', entity_id=invitation_id, read=False, created_at=sa.func.current_timestamp()))
    op.execute(sa.text("UPDATE roommate_requests SET status = 'cancelled', active_pair_key = NULL, reason = 'policy_upgrade' WHERE status = 'pending'"))
    # Preserve existing occupancy and flag it for explicit operator reconciliation.
    op.execute(sa.text("""INSERT INTO pilot_allocation_history (user_id, group_id, room_id, opened_at)
        SELECT gm.user_id, gm.group_id, ra.room_id, ra.assigned_at FROM group_members gm
        JOIN room_assignments ra ON ra.group_id = gm.group_id"""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    raise RuntimeError("Pilot cutover cannot be safely reversed by schema downgrade; use a reviewed compatible release or controlled restore")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_email')
    op.drop_column('users', 'consent_version')
    op.drop_column('users', 'explanation_consent')
    op.drop_column('users', 'discovery_consent')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'auth_version')
    op.drop_column('rooms', 'reconciliation_required')
    op.drop_column('rooms', 'cycle')
    op.drop_column('rooms', 'pool')
    op.drop_column('groups', 'reconciliation_required')
    op.drop_column('groups', 'cycle')
    op.drop_column('groups', 'pool')
    op.drop_column('groups', 'membership_revision')
    op.drop_index('ix_pilot_outbox_due', table_name='pilot_outbox')
    op.drop_table('pilot_outbox')
    op.drop_index(op.f('ix_pilot_security_tokens_user_id'), table_name='pilot_security_tokens')
    op.drop_index(op.f('ix_pilot_security_tokens_expires_at'), table_name='pilot_security_tokens')
    op.drop_index(op.f('ix_pilot_security_tokens_enrollment_id'), table_name='pilot_security_tokens')
    op.drop_table('pilot_security_tokens')
    op.drop_index(op.f('ix_pilot_invitation_participants_user_id'), table_name='pilot_invitation_participants')
    op.drop_table('pilot_invitation_participants')
    op.drop_index(op.f('ix_pilot_support_cases_user_id'), table_name='pilot_support_cases')
    op.drop_table('pilot_support_cases')
    op.drop_index(op.f('ix_pilot_sessions_user_id'), table_name='pilot_sessions')
    op.drop_index(op.f('ix_pilot_sessions_expires_at'), table_name='pilot_sessions')
    op.drop_table('pilot_sessions')
    op.drop_table('pilot_questionnaires')
    op.drop_index(op.f('ix_pilot_notifications_user_id'), table_name='pilot_notifications')
    op.drop_table('pilot_notifications')
    op.drop_index(op.f('ix_pilot_invitations_initiator_id'), table_name='pilot_invitations')
    op.drop_index(op.f('ix_pilot_invitations_group_id'), table_name='pilot_invitations')
    op.drop_index(op.f('ix_pilot_invitations_candidate_id'), table_name='pilot_invitations')
    op.drop_index('ix_pilot_invitation_status_expiry', table_name='pilot_invitations')
    op.drop_table('pilot_invitations')
    op.drop_table('pilot_enrollments')
    op.drop_index(op.f('ix_pilot_domain_audit_created_at'), table_name='pilot_domain_audit')
    op.drop_index(op.f('ix_pilot_domain_audit_action'), table_name='pilot_domain_audit')
    op.drop_table('pilot_domain_audit')
    op.drop_index(op.f('ix_pilot_departures_user_id'), table_name='pilot_departures')
    op.drop_table('pilot_departures')
    op.drop_index(op.f('ix_pilot_command_receipts_created_at'), table_name='pilot_command_receipts')
    op.drop_table('pilot_command_receipts')
    op.drop_index(op.f('ix_pilot_blocks_target_id'), table_name='pilot_blocks')
    op.drop_index(op.f('ix_pilot_blocks_actor_id'), table_name='pilot_blocks')
    op.drop_table('pilot_blocks')
    op.drop_index(op.f('ix_pilot_allocation_history_user_id'), table_name='pilot_allocation_history')
    op.drop_index(op.f('ix_pilot_allocation_history_closed_at'), table_name='pilot_allocation_history')
    op.drop_table('pilot_allocation_history')
    op.drop_table('pilot_worker_heartbeats')
    op.drop_index(op.f('ix_pilot_rate_buckets_expires_at'), table_name='pilot_rate_buckets')
    op.drop_table('pilot_rate_buckets')
    op.drop_table('pilot_deletion_ledger')
    # ### end Alembic commands ###
